definitions:
  models.CreateUserModel:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.StandardErrorModel:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
  models.UserModel:
    properties:
      age:
        type: integer
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/user/create-user/:
    post:
      consumes:
      - application/json
      description: CreateUser API is for crete new user
      parameters:
      - description: create_user
        in: body
        name: create_user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: Create User
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
